import {SPOTIFY_CLIENT_ID, SPOTIFY_AUTHORIZATION_ENDPOINT, SPOTIFY_SCOPES, REDIRECT_URI_SCHEME, BASE_URL } from "@env";
export const apiConfig={
    clientId:SPOTIFY_CLIENT_ID,
    endpoint:SPOTIFY_AUTHORIZATION_ENDPOINT,
    scopes:SPOTIFY_SCOPES,
    redirectUri:REDIRECT_URI_SCHEME,
    baseUrl:BASE_URL
}
